[build]
  base = "."
  publish = "public"
  functions = "netlify/functions"
  command = "npm start" # Install dependencies (Netlify will automatically detect)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
